backend:
  name: github
  repo: GOPODC/cld-seit
  branch: main
  base_url: https://github-proxy-api.vercel.app

media_folder: "/"
public_folder: "/"

collections:
  - name: "pages"
    label: "Pagini"
    files:
      - file: "index.html"
        label: "Pagina PrincipalÄƒ"
        name: "index"
        fields:
          - {label: "Titlu Site", name: "title", widget: "string"}
          - {label: "Descriere", name: "description", widget: "text"}
