backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Location", name: "location", widget: "string"}
