backend:
  name: github
  repo: GOPODC/cld-seit
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth
  app_id: AICI_PUI_CODUL_TAU_CLIENT_ID

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gaming"
    label: "Gaming PCs"
    folder: "_posts/gaming"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
