backend:
  name: github
  repo: utilizatorul-tau/nume-proiect  # AICI trebuie să fie numele TĂU real de pe GitHub
  branch: main

collections:
  - name: "pages"
    label: "Pagini"
    files:
      - file: "index.html"
        label: "Pagina Principală"
        name: "index"
        fields:
          - {label: "Titlu Site", name: "title", widget: "string"}
          - {label: "Descriere", name: "description", widget: "text"}


