backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "setari"
    label: "Setări Site"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Informații Contact"
        file: "index.html"
        fields:
          - {label: "Titlu Site", name: "titlu", widget: "string"}
          - {label: "Email Contact", name: "email", widget: "string"}
          - {label: "Locație", name: "locatie", widget: "string"}
