backend:
  name: github
  repo: GOPODC/cld-seit
  branch: main
  # Folosim un alt "paznic" (proxy) care este liber È™i nu te-a blocat
  base_url: https://paznic-cms.vercel.app 
  auth_endpoint: /api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gaming"
    label: "Gaming PCs"
    folder: "_posts/gaming"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
