backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "img"

collections:
  - name: "pc_builds"
    label: "Meine PC-Systeme" # Sec»õiunea ta de calculatoare
    folder: "content/builds"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Modellname", name: "title", widget: "string"}
      - {label: "PC Bild", name: "image", widget: "image"}
      - {label: "Beschreibung/Details", name: "body", widget: "markdown"}
      - {label: "Preis", name: "pret", widget: "string"}

  - name: "contact"
    label: "Kontakt Informationen"
    files:
      - name: "date_contact"
        label: "Kontakt bearbeiten"
        file: "index.html"
        fields:
          - {label: "E-Mail", name: "email", widget: "string"}
          - {label: "Standort", name: "locatie", widget: "string"}
