backend:
  name: github
  repo: GopoDC/cld-seit  # VERIFICĂ DACĂ ACESTA E NUMELE TĂU DE UTILIZATOR ȘI REPO
  branch: main
  base_url: https://cld-seit.vercel.app
  auth_endpoint: api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pagini"
    label: "Pagini Site"
    folder: "public"
    create: true
    fields:
      - {label: "Titlu", name: "title", widget: "string"}
      - {label: "Corp Pagina", name: "body", widget: "markdown"}

