backend:
  name: github
  repo: GopoDC/cld-seit
  branch: main
  base_url: https://pwa-auth-proxy.vercel.app
  auth_endpoint: api/v1/authorize

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pagini"
    label: "Pagini"
    folder: "public"
    extension: "html"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Titlu", name: "title", widget: "string"}
      - {label: "Corp", name: "body", widget: "markdown"}
