backend:
  name: github
  repo: GopoDC/cld-seit
  branch: main
  site_domain: cld-seit.vercel.app
  base_url: https://pww-decaps-proxy.vercel.app
  auth_endpoint: api/v1/authorize

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pagini"
    label: "Pagini Site"
    folder: "public"
    extension: "html"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Titlu", name: "title", widget: "string"}
      - {label: "Corp Pagina", name: "body", widget: "markdown"}
